version: "2"
linters:
  default: none
  enable:
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 120
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - exitAfterDefer
        - whyNoLint
        - singleCaseSwitch
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    depguard:
      rules:
        main:
          list-mode: original
          allow:
            - $gostd
            - github.com/TotallyGamerJet/win32metadat
            - github.com/stretchr/testify
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocritic
        text: commentedOutCode
        source: SHA1
      - linters:
          - gochecknoglobals
        source: embed\.FS
      - linters:
          - lll
        source: //go:generate
      - linters:
          - dupl
          - errcheck
          - funlen
          - gochecknoglobals
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - lll
          - scopelint
        path: _test\.go
      - linters:
          - govet
        text: declaration of "(err|ctx|log)"
      - linters:
          - golint
        path: internal\.go
        text: should have.+comment
      - linters:
          - revive
          - staticcheck
        text: use ALL_CAPS in Go names; use CamelCase
      - linters:
          - revive
          - staticcheck
        text: struct field .*Id should be .*ID
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
